### ISSUE TITLE
k8s对象定义

### ISSUE THREAD

**Issue by zhouyh139** [ianherman/blog#1]
# 一个简单的Pod定义
pod.yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
   name: pod-nginx
   labels:
     app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.7.9
      ports:
        - containerPort: 80
```
# 一个简单的deployment定义
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  labels:
      app1: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
       app2: nginx
  template:
    metadata:
       labels:
          app2: nginx
    spec:
       containers:
         - name: nginx
           image: nginx:1.7.9
           ports:
             - containerPort: 80
```
